## BOILERPLATE

esphome:
  name: atom-matrix
  friendly_name: "Matrix"
  comment: "M5Stack ATOM Matrix for LED status updates in the Living Room"

esp32:
  board: m5stack-atom
  framework:
    type: arduino

logger:

wifi:
  networks: !secret wifi

api:
  encryption:
    key: "JNj7PgqTdG1lCKrqJNK3bMwSIsQ4Hvv+O9bvngbCZ0s="

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: time_now

## STANDARD BLE PROXY SETUP
# Disabled because we don't need one in the living room yet

# esp32_ble_tracker:
#   scan_parameters:
#     interval: 1100ms
#     window: 1100ms
#     active: true

# bluetooth_proxy:
#   active: true

## HARDWARE

sensor:
  - platform: internal_temperature
    name: "CPU temperature"
  - platform: wifi_signal
    id: wifi_signal_stringth
    name: "Signal strength"
    update_interval: 5s

button:
  - platform: safe_mode
    name: "Reboot safe mode"
    entity_category: diagnostic
  - platform: restart
    name: "Reboot"
    entity_category: diagnostic

binary_sensor:
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: Button
    on_press:
      then:
        - light.toggle: matrix_light

light:
  - platform: fastled_clockless # 5x5 RGB Matrix (WS2812C)
    chipset: WS2812
    pin: 27
    num_leds: 25
    rgb_order: GRB
    name: "Display"
    id: matrix_light
    color_correct: [30%, 30%, 30%] # Limit LED power to avoid damage to the matrix
    default_transition_length: 0s
    internal: true

# display:
#   - platform: addressable_light
#     addressable_light_id: matrix_light
#     id: matrix_display
#     height: 5
#     width: 5
#     rotation: 180 # USB port is at the bottom
#     update_interval: 2s
#     lambda: |-
#       it.fill(COLOR_ON);
display:
  - platform: addressable_light
    id: matrix_display
    addressable_light_id: matrix_light
    width: 5
    height: 5
    rotation: 0° # USB port is at the bottom
    # update_interval: 16ms
    update_interval: 0.5s
    # show_test_card: true
    lambda: |-
      it.fill(COLOR_OFF);
      Color red = Color(0xFF0000);
      Color green = Color(0x00FF00);
      Color blue = Color(0x0000FF);
      auto time = id(time_now).now();
      // int day = time.day_of_month;
      int day = id(day_override).state;
      if (day == 0 || time.year == 1970) {
        // Hack: If the year is 1970, we probably just haven't got a time from Home Assistant yet
        it.filled_rectangle(0, 0, 5, 5, red);
        return;
      }
      Color color = green;
      // Draw filled rows
      int full_rows = (day - 1) / 5; // Subtract 1 from `day` to account for the blinky pixel
      it.filled_rectangle(0, 0, 5, full_rows, color);
      // Draw the solid pixels for the bottom row
      int remaining_pixels = (day - 1) % 5; // Again, excluding the blinky pixel
      int solid_pixels = remaining_pixels - 1;
      //ESP_LOGD("date_display", "solid_pixels=%d", remaining_pixels);
      if (remaining_pixels >= 0) {
        it.filled_rectangle(0, full_rows, remaining_pixels, 1, color);
        ESP_LOGD("date_display", "%d remaining, drawing rect (%d, %d, %d, %d)", 0, full_rows, remaining_pixels, 1);
      }
      // Draw the blinky pixel for the bottom row
      ESP_LOGD("date_display", "Special pixel @ (%d, %d)", remaining_pixels, full_rows);
      it.draw_pixel_at(remaining_pixels, full_rows, red);

      // ESP_LOGD("date_display", "Current day: %02d", day);
      // ESP_LOGD("main", "Value of my datetime: %04d-%02d-%02d %0d:%02d:%02d",
      //    time.year, time.month, time.day_of_month,
      //    time.hour, time.minute, time.second);

## DEVICE STATE

select:
  - platform: template
    id: mode
    name: "Mode"
    optimistic: true
    options:
      - Christmas
      - Wifi signal
      - Disabled
    initial_option: Christmas

number:
  - platform: template
    optimistic: true
    min_value: 1
    max_value: 25
    step: 1
    id: day_override
    name: Current day
