esphome:
  name: dirt
  comment: A dirt-cheap ESP8266 board for testing stuff
  friendly_name: Dirt ESP

# Board: https://www.aliexpress.com/item/1005006307170375.html "Wireless Module CH340/CP2102 NodeMcu V3 V2 Lua WIFI Internet of Things Develop Board based ESP8266 ESP-12E with PCB Antenna" "V3 CH340 With Cable"

esp8266:
  board: nodemcuv2

logger:

api:
  encryption:
    key: !secret api_key_dirt

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  networks: !secret wifi

text_sensor:
  - platform: wifi_info
    ssid:
      name: SSID
      entity_category: diagnostic
  - platform: version
    name: "Firmware"
    entity_category: diagnostic

sensor:
  - platform: wifi_signal
    name: "Signal strength"
    update_interval: 10s

switch:
  - platform: gpio
    pin:
      number: D0
      mode:
        output: true
    id: pulldown_0
    name: GPIO 0
  - platform: gpio
    pin:
      number: D1
      mode:
        output: true
    id: pulldown_1
    name: GPIO 1
  - platform: gpio
    pin:
      number: D2
      mode:
        output: true
    id: pulldown_2
    name: GPIO 2
  - platform: gpio
    pin:
      number: D3
      mode:
        output: true
    id: pulldown_3
    name: GPIO 3
