# DEVICE=/dev/seeed-cherry

## Boilerplate for Seeed boards

esphome:
  name: seeed-cherry
  friendly_name: Seeed cherry
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: esp-idf

logger:
  hardware_uart: USB_SERIAL_JTAG

## WiFi stuff

wifi:
  ap:
    ssid: "Seeed birch"
    channel: 6
  power_save_mode: none

ota:
  password: !secret ota_password

web_server:
  port: 80
  include_internal: True
  ota: False
  local: True

sensor:
  ## CPU temperature monitoring
  - platform: internal_temperature
    name: "CPU temperature"
  ## Diagnostic sensors
  - platform: internal_temperature
    name: "CPU temperature"

text_sensor:
  ## Diagnostic text sensors
  - platform: version
    name: "Firmware"
    entity_category: diagnostic