esphome:
  name: super-mini-s3
  comment: ESP32 dev board that powers a Cube Clock speaker
  friendly_name: SuperMini S3

esp32:
  variant: ESP32S3
  framework:
    type: esp-idf

psram:
  ignore_not_found: false
  mode: quad

logger:

api:
  encryption:
    key: !secret api_key_super_mini_s3

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks: !secret wifi

debug:
  update_interval: 5min

sensor:
  - platform: internal_temperature
    name: "CPU temperature"
  - platform: wifi_signal
    name: "Signal strength"
    update_interval: 60s
  - platform: debug
    free:
      name: "Heap memory free"
    cpu_frequency:
      name: "CPU frequency"
    psram:
      name: "PSRAM free"

runtime_stats:
  log_interval: 60s

## Media source
sendspin:

media_source:
  - platform: sendspin
    # buffer_size: 50_000
    # sample_rate: 32_000
    id: sendspin_media_source

## Speaker

i2s_audio:
  i2s_lrclk_pin: 13
  i2s_bclk_pin: 11

speaker:
  - platform: i2s_audio
    id: i2s_output
    dac_type: external
    i2s_dout_pin: 12
    channel: stereo
    # buffer_duration: 100ms

media_player:
  - platform: speaker_source
    id: external_media_player
    name: Speaker
    media_pipeline:
      speaker: i2s_output
      sources:
        - sendspin_media_source

## LED on the devboard

light:
  - platform: esp32_rmt_led_strip
    name: "LED"
    rgb_order: GRB
    pin: 48
    chipset: WS2811
    num_leds: 1
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF
