# Product: https://www.aliexpress.com/item/1005005626813706.html "TZT ESP32 Lite V1.0.0 Wifi Bluetooth Development Board ESP32 ESP-32 REV1 CH340G MicroPython 4MB Micro/TYPE-C USB For Arduino"

esphome:
  name: tzt-lite
  comment: ESP32 dev board that powers a Cube Clock speaker
  friendly_name: Cube Clock

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_key_tzt_lite

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks: !secret wifi

debug:
  update_interval: 5s

sensor:
  - platform: internal_temperature
    name: "CPU temperature"
  #   - platform: wifi_signal
  #     name: "Signal strength"
  #     update_interval: 60s
  - platform: debug
    free:
      name: "Heap memory free"
    block:
      name: "Largest contiguous free heap block"

## Media source
sendspin:

media_source:
  - platform: sendspin
    buffer_size: 50_000
    sample_rate: 32_000
    id: sendspin_media_source

## Speaker

i2s_audio:
  i2s_lrclk_pin: 26
  i2s_bclk_pin: 27

speaker:
  - platform: i2s_audio
    id: main_speaker
    dac_type: external
    i2s_dout_pin: 14
    channel: mono
    buffer_duration: 100ms

media_player:
  - platform: speaker_source
    id: external_media_player
    name: Audio
    media_pipeline:
      speaker: main_speaker
      sources:
        - sendspin_media_source
      format: MP3

## LED on the devboard

output:
  - platform: ledc
    pin: 22
    id: board_led
    inverted: true

light:
  - platform: status_led
    output: board_led
    name: "Status LED"
    restore_mode: RESTORE_DEFAULT_OFF
