# Product: https://www.aliexpress.com/item/1005005626813706.html "TZT ESP32 Lite V1.0.0 Wifi Bluetooth Development Board ESP32 ESP-32 REV1 CH340G MicroPython 4MB Micro/TYPE-C USB For Arduino"

esphome:
  name: tzt-lite
  comment: ESP32 dev board that powers a Cube Clock speaker
  friendly_name: Cube Clock

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_key_tzt_lite

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks: !secret wifi

sensor:
  - platform: internal_temperature
    name: "CPU temperature"
  - platform: wifi_signal
    name: "Signal strength"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ssid:
      name: SSID
      entity_category: diagnostic

button:
  - platform: safe_mode
    name: "Reboot safe mode"
    entity_category: diagnostic
  - platform: restart
    name: "Reboot"
    entity_category: diagnostic

## Media source
sendspin:

media_source:
  - platform: sendspin
    id: sendspin_media_source

## Speaker

i2s_audio:
  i2s_lrclk_pin: 26
  i2s_bclk_pin: 27

speaker:
  - platform: i2s_audio
    id: main_speaker
    dac_type: external
    i2s_dout_pin: 14
    channel: mono
  - platform: mixer
    output_speaker: main_speaker
    source_speakers:
      - id: announcement_speaker
      - id: media_speaker

media_player:
  - platform: speaker
    id: external_media_player
    name: Audio
    buffer_size: 40_000
    media_pipeline:
      speaker: media_speaker
      format: MP3
    announcement_pipeline:
      speaker: announcement_speaker
      format: MP3

## LED on the devboard

output:
  - platform: ledc
    pin: 22
    id: board_led
    inverted: true

light:
  - platform: status_led
    output: board_led
    name: "Status LED"
    restore_mode: RESTORE_DEFAULT_OFF
